### PR TITLE
Publish vendored Thrift as separate package without ASP.NET Core dependencies

### PR DESCRIPTION
**Pull request by cwe1ss**
See #35.

This PR does the following things:
* Thrift has been changed to no longer have dependencies on any non-standard libraries. I only had to remove two files and change two files for this (from the unused "Server" part and the project file itself) so merging changes from the official repo shouldn't be much harder.
* Thrift is no longer IL-merged as we are having issues with that on macOS and it also shows some errors in Visual Studio. Instead it is published as a separate package - currently named "Jaeger.Thrift.VendoredThrift" (I'm open to other naming suggestions). The assembly name will be the same, so there won't be any conflicts with other Thrift libraries.
* We should obviously remove that package as soon as there's a proper official Thrift library.

This is a bad solution as well so I'm not sure if we should do that. Instead of publishing the modified version as a separate package, I can also try to fix the IL-merge problems.

### CODE REVIEW

**Comment by grounded042** [comment]
Wow, that was not a lot of code to be able to drop 9 dependencies.

**Comment by Falco20019** [comment]
Have you checked if there is any other NuGET library for Thrift that targets `.netstandard2.0` that we could use? Would be the cleaner option. Didn't have a lot of time today, but if noone has checked, I would look it up tomorrow.

But interesting to see how little code is depending on those 9 packages. Apache should really pack those into a separate package as you proposed.

**Comment by grounded042** [comment]
I did some poking around and am not finding a good library on NuGet for Thrift. I do like the way this is done - we are not making a Thrift package for anyone but are instead tying it to this project. I'm gonna chat with @kevindaviscfc about this PR, but I think we should do a merge and move forward.

**Comment by grounded042** [comment]
@cwe1ss could you look at why the AppVeyor build is failing?

**Comment by grounded042** [comment]
Once we get the PR build working we'll go ahead and merge this in. I chatted with @kevindaviscfc and we agree that this is not an ideal solution, but until Thrift publishes an official package and one that can break apart the server and client we should go with this approach.

**Pull request merged**
